// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiTmMqL783x5T8iBK9bXOD6CIbu4j08OI',
    appId: '1:925607175747:web:1c061ae3d8c5dfd45296f6',
    messagingSenderId: '925607175747',
    projectId: 'fast-color-printer',
    authDomain: 'fast-color-printer.firebaseapp.com',
    storageBucket: 'fast-color-printer.firebasestorage.app',
    measurementId: 'G-XE9GHXS71K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbzj_rtQgu1PeLaJ--7meh87vFcTu3p64',
    appId: '1:925607175747:android:562d70b9f636e2485296f6',
    messagingSenderId: '925607175747',
    projectId: 'fast-color-printer',
    storageBucket: 'fast-color-printer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxi5EQBeaZYsyGRwEmM-kkcajGbctabrc',
    appId: '1:925607175747:ios:d1810b6ef8cf613d5296f6',
    messagingSenderId: '925607175747',
    projectId: 'fast-color-printer',
    storageBucket: 'fast-color-printer.firebasestorage.app',
    iosBundleId: 'com.example.fastColorPrinter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxi5EQBeaZYsyGRwEmM-kkcajGbctabrc',
    appId: '1:925607175747:ios:d1810b6ef8cf613d5296f6',
    messagingSenderId: '925607175747',
    projectId: 'fast-color-printer',
    storageBucket: 'fast-color-printer.firebasestorage.app',
    iosBundleId: 'com.example.fastColorPrinter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiTmMqL783x5T8iBK9bXOD6CIbu4j08OI',
    appId: '1:925607175747:web:e7fb8e42b3c1f5995296f6',
    messagingSenderId: '925607175747',
    projectId: 'fast-color-printer',
    authDomain: 'fast-color-printer.firebaseapp.com',
    storageBucket: 'fast-color-printer.firebasestorage.app',
    measurementId: 'G-8YYGVFCD5P',
  );
}
